spring.application.name=DeliveryManagement
spring.jackson.default-property-inclusion=non_null
spring.jackson.property-naming-strategy=SNAKE_CASE
spring.datasource.url=jdbc:postgresql://${DATABASE_URL:localhost}:${DATABASE_PORT:5432}/ddma
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:secret}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=never
